baseURL = "http://acornapps.github.io/cocktail-manual-3.3.0-public"
languageCode = "kr-ko"
title = "칵테일 클라우드"
theme = "hugo-theme-learn"

[author]
    name = "cloud.jung"
    email = "cloud.jung@acornsoft.io"

[params]
    imageRootDir = "/cocktail-manual-3.3.0-public/images"
    version = "3.1.1"
