baseURL = "http://acornapps.github.io"
languageCode = "kr-ko"
title = "칵테일 클라우드"
theme = "hugo-theme-learn"

disqusShortname = "XXXXXXXXXXXXXXX"

googleAnalytics = "UA-XXXXXXXXXX-X"

paginate = 7


[author]
    name = "cloud.jung"
    email = "cloud.jung@acornsoft.io"

[params]
    baseurl = "/images"
    version = "3.1.1"
