baseURL = "http://acornapps.github.io"
languageCode = "kr-ko"
title = "$HELLO_PROG^"
theme = "hugo-theme-learn"

disqusShortname = "XXXXXXXXXXXXXXX"

googleAnalytics = "UA-XXXXXXXXXX-X"

paginate = 7

[author]
    name = "cloud.jung"
    email = "cloud.jung@acornsoft.io"
